"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowLeft, Camera, CheckCircle2, LoaderCircle, Mail, Save, ShieldCheck, Upload } from "lucide-react";

const API = "https://api.escuelajs.co/api/v1";
const fallback = { id: "", name: "Admin", email: "admin@mail.com", role: "admin", avatar: "https://i.imgur.com/LDOO4Qs.jpg" };

export default function AdminProfilePage() {
  const [profile, setProfile] = useState(fallback); const [avatar, setAvatar] = useState(fallback.avatar); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const inputRef = useRef(null);
  useEffect(() => { const saved = JSON.parse(localStorage.getItem("user") || "null"); const savedAvatar = localStorage.getItem("admin_avatar"); const current = { ...fallback, ...saved, avatar: savedAvatar || saved?.avatar || fallback.avatar }; setProfile(current); setAvatar(current.avatar); setLoading(false); }, []);
  function update(e) { setProfile({ ...profile, [e.target.name]: e.target.value }); }
  async function chooseImage(e) { const file = e.target.files?.[0]; if (!file) return; const body = new FormData(); body.append("file", file); try { const response = await fetch("/api/admin/profile-photo", { method: "POST", body }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Upload failed."); setAvatar(result.location); localStorage.setItem("admin_avatar", result.location); } catch (error) { setMessage(error.message); } finally { e.target.value = ""; } }
  async function save(e) { e.preventDefault(); setSaving(true); setMessage(""); const updated = { ...profile, avatar }; try { if (profile.id) { const token = localStorage.getItem("access_token"); await fetch(`${API}/users/${profile.id}`, { method: "PUT", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ name: profile.name, email: profile.email, avatar }) }); } localStorage.setItem("user", JSON.stringify(updated)); setProfile(updated); setMessage("Profile updated successfully."); } catch { setMessage("Saved locally. API sync was unavailable."); } finally { setSaving(false); } }
  if (loading) return <div className="flex justify-center py-20"><LoaderCircle className="animate-spin text-[#e96546]" /></div>;
  return <div className="max-w-4xl mx-auto space-y-7"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-[#777064] hover:text-[#e96546]"><ArrowLeft size={16} /> Back to dashboard</Link><header><p className="eyebrow text-[#e96546] mb-2">Account settings</p><h1 className="display-type text-4xl font-bold">Edit admin profile</h1><p className="text-[#777064] mt-2">Update the details your team sees in the admin workspace.</p></header><form onSubmit={save} className="grid lg:grid-cols-[280px_1fr] gap-6"><section className="bg-[#2d2924] text-white rounded-2xl p-6 text-center h-fit"><div className="relative mx-auto w-32 h-32"><Image src={avatar} alt={profile.name} width={128} height={128} className="w-32 h-32 rounded-full object-cover border-4 border-white/20" unoptimized /><button type="button" onClick={() => inputRef.current?.click()} className="absolute right-0 bottom-1 rounded-full bg-[#e96546] p-3 hover:bg-[#f27d61]"><Camera size={18} /></button></div><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" onChange={chooseImage} className="hidden" /><h2 className="mt-5 text-xl font-bold">{profile.name}</h2><p className="text-white/60 text-sm mt-1">{profile.email}</p><button type="button" onClick={() => inputRef.current?.click()} className="mt-5 w-full inline-flex justify-center items-center gap-2 rounded-xl border border-white/20 py-3 text-sm font-semibold hover:bg-white/10"><Upload size={16} /> Upload photo</button><p className="text-[11px] text-white/40 mt-3">PNG, JPG, WEBP · max 3 MB</p></section><section className="bg-[#fbf8f2] border border-[#dfd7ca] rounded-2xl p-6 sm:p-8 space-y-5"><label className="block text-sm font-semibold">Full name<input name="name" value={profile.name} onChange={update} className="admin-input" /></label><label className="block text-sm font-semibold">Email address<div className="relative"><Mail size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#a29a90]" /><input name="email" type="email" value={profile.email} onChange={update} className="admin-input pl-11" /></div></label><div className="grid sm:grid-cols-2 gap-4"><div className="rounded-xl bg-white border border-[#e5ded3] p-4"><p className="text-xs text-[#a29a90]">Role</p><p className="mt-2 font-bold text-[#c44d3d] flex items-center gap-2"><ShieldCheck size={16} /> Administrator</p></div><div className="rounded-xl bg-white border border-[#e5ded3] p-4"><p className="text-xs text-[#a29a90]">Status</p><p className="mt-2 font-bold text-[#3f9d70]">Active</p></div></div>{message && <p className="flex items-center gap-2 text-sm text-[#3f9d70]"><CheckCircle2 size={17} />{message}</p>}<button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#2d2924] text-white px-6 py-3.5 font-semibold hover:bg-[#e96546] disabled:opacity-60"><Save size={17} />{saving ? "Saving…" : "Save changes"}</button></section></form></div>;
}
