"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import { Plus, Pencil, Trash2, Tags, LoaderCircle } from "lucide-react";

const API = "https://api.escuelajs.co/api/v1";

export default function CategoriesAdminPage() {
  const [categories, setCategories] = useState([]); const [form, setForm] = useState({ name: "", image: "https://placehold.co/600x400" }); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const load = () => fetch(`${API}/categories`).then((r) => r.json()).then(setCategories).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  async function save(event) { event.preventDefault(); const url = editing ? `${API}/categories/${editing}` : `${API}/categories/`; const response = await fetch(url, { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (response.ok) { setMessage(editing ? "Category updated." : "Category created."); setForm({ name: "", image: "https://placehold.co/600x400" }); setEditing(null); load(); } else setMessage("Could not save category."); }
  async function remove(id) { if (!window.confirm("Delete this category?")) return; const response = await fetch(`${API}/categories/${id}`, { method: "DELETE" }); if (response.ok) setCategories((items) => items.filter((item) => item.id !== id)); }

  return <div className="space-y-7"><header><p className="eyebrow text-[#e96546] mb-2">Catalog structure</p><h1 className="display-type text-4xl font-bold">Categories</h1><p className="text-[#777064] mt-2">Organize the storefront and manage category records through the API.</p></header><div className="grid xl:grid-cols-[.75fr_1.25fr] gap-6"><form onSubmit={save} className="bg-[#2d2924] text-white rounded-2xl p-6 h-fit"><p className="eyebrow text-[#f7a18d] mb-2">{editing ? "Update category" : "New category"}</p><h2 className="text-xl font-bold mb-5">{editing ? "Edit category" : "Create a category"}</h2><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Category name" className="w-full rounded-xl bg-white/10 border border-white/15 px-4 py-3 outline-none placeholder:text-white/40 focus:border-[#f7a18d]" /><input required value={form.image} onChange={(e) => setForm({ ...form, image: e.target.value })} placeholder="Image URL" className="w-full rounded-xl bg-white/10 border border-white/15 px-4 py-3 outline-none placeholder:text-white/40 focus:border-[#f7a18d] mt-3" /><button className="mt-4 w-full rounded-xl bg-[#e96546] py-3 font-semibold hover:bg-[#f27d61]">{editing ? "Save changes" : "Create category"}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm({ name: "", image: "https://placehold.co/600x400" }); }} className="w-full mt-3 text-sm text-white/60">Cancel editing</button>}</form><div className="bg-[#fbf8f2] border border-[#dfd7ca] rounded-2xl overflow-hidden"><div className="px-5 py-4 border-b border-[#e5ded3] flex justify-between"><p className="font-semibold">All categories <span className="text-[#a29a90] font-normal">({categories.length})</span></p>{message && <p className="text-xs text-[#3f9d70]">{message}</p>}</div>{loading ? <div className="p-14 flex justify-center"><LoaderCircle className="animate-spin text-[#e96546]" /></div> : <div className="divide-y divide-[#e5ded3]">{categories.map((category) => <div key={category.id} className="p-4 flex items-center gap-4"><Image src={category.image} alt={category.name} width={56} height={56} className="w-14 h-14 rounded-xl object-cover" /><div className="flex-1"><p className="font-semibold">{category.name}</p><p className="text-xs text-[#a29a90]">/{category.slug}</p></div><button onClick={() => { setEditing(category.id); setForm({ name: category.name, image: category.image }); }} className="p-2 text-[#5c78d8] hover:bg-[#e9edfb] rounded-lg"><Pencil size={17} /></button><button onClick={() => remove(category.id)} className="p-2 text-[#d65b4c] hover:bg-[#fbe8e5] rounded-lg"><Trash2 size={17} /></button></div>)}{!categories.length && <div className="p-14 text-center text-[#777064]"><Tags className="mx-auto mb-3" />No categories yet.</div>}</div>}</div></div></div>;
}
