"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, LoaderCircle, Plus } from "lucide-react";

const API = "https://api.escuelajs.co/api/v1";

export default function AddProduct() {
  const router = useRouter(); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [product, setProduct] = useState({ title: "", price: "", description: "", categoryId: "", images: "" });
  useEffect(() => { fetch(`${API}/categories`).then((r) => r.json()).then(setCategories); }, []);
  const update = (e) => setProduct({ ...product, [e.target.name]: e.target.value });
  async function submit(e) { e.preventDefault(); setLoading(true); setError(""); try { const res = await fetch(`${API}/products/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: product.title, price: Number(product.price), description: product.description, categoryId: Number(product.categoryId), images: [product.images] }) }); if (!res.ok) throw new Error("Could not create product."); router.push("/admin/products"); } catch (err) { setError(err.message); setLoading(false); } }
  return <div className="max-w-4xl mx-auto space-y-7"><Link href="/admin/products" className="inline-flex items-center gap-2 text-sm font-semibold text-[#777064] hover:text-[#e96546]"><ArrowLeft size={16} /> Back to products</Link><header><p className="eyebrow text-[#e96546] mb-2">Catalog management</p><h1 className="display-type text-4xl font-bold">Add a product</h1><p className="text-[#777064] mt-2">Create a new item in the live Platzi catalog.</p></header><form onSubmit={submit} className="bg-[#fbf8f2] border border-[#dfd7ca] rounded-2xl p-6 sm:p-8 space-y-5"><div className="grid sm:grid-cols-2 gap-5"><label className="block text-sm font-semibold">Product title<input required name="title" value={product.title} onChange={update} placeholder="e.g. Classic linen shirt" className="admin-input" /></label><label className="block text-sm font-semibold">Price<input required min="0" step="0.01" type="number" name="price" value={product.price} onChange={update} placeholder="0.00" className="admin-input" /></label></div><label className="block text-sm font-semibold">Category<select required name="categoryId" value={product.categoryId} onChange={update} className="admin-input"><option value="">Choose a category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="block text-sm font-semibold">Description<textarea required name="description" value={product.description} onChange={update} placeholder="Describe the product..." rows={5} className="admin-input resize-y" /></label><label className="block text-sm font-semibold">Image URL<input required type="url" name="images" value={product.images} onChange={update} placeholder="https://..." className="admin-input" /></label>{error && <p className="text-sm text-red-600">{error}</p>}<button disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#2d2924] text-white px-6 py-3.5 font-semibold hover:bg-[#e96546] disabled:opacity-60">{loading ? <LoaderCircle size={17} className="animate-spin" /> : <Plus size={17} />} {loading ? "Creating..." : "Create product"}</button></form></div>;
}
